"use strict"

var TYPE = {
  LIGHT: 1,
  NORMAL: 2,
  DARK: 3,
  RED: 4,
  YELLOW: 5,
  GREEN: 6,
  CYAN: 7,
  BLUE: 8,
  MAGENTA: 9,
  WHITE: 10,
  BLACK: 11,
};

var COLOR = {
  LIGHT_RED:[TYPE.LIGHT, TYPE.RED],
  LIGHT_YELLOW:[TYPE.LIGHT, TYPE.YELLOW],
  LIGHT_GREEN:[TYPE.LIGHT, TYPE.GREEN],
  LIGHT_CYAN:[TYPE.LIGHT, TYPE.CYAN],
  LIGHT_BLUE:[TYPE.LIGHT, TYPE.BLUE],
  LIGHT_MAGENTA:[TYPE.LIGHT, TYPE.MAGENTA],
  NORMAL_RED:[TYPE.NORMAL, TYPE.RED],
  NORMAL_YELLOW:[TYPE.NORMAL, TYPE.YELLOW],
  NORMAL_GREEN:[TYPE.NORMAL, TYPE.GREEN],
  NORMAL_CYAN:[TYPE.NORMAL, TYPE.CYAN],
  NORMAL_BLUE:[TYPE.NORMAL, TYPE.BLUE],
  NORMAL_MAGENTA:[TYPE.NORMAL, TYPE.MAGENTA],
  DARK_RED:[TYPE.DARK, TYPE.RED],
  DARK_YELLOW:[TYPE.DARK, TYPE.YELLOW],
  DARK_GREEN:[TYPE.DARK, TYPE.GREEN],
  DARK_CYAN:[TYPE.DARK, TYPE.CYAN],
  DARK_BLUE:[TYPE.DARK, TYPE.BLUE],
  DARK_MAGENTA:[TYPE.DARK, TYPE.MAGENTA],
  NORMAL_WHITE:[TYPE.NORMAL, TYPE.WHITE],
  NORMAL_BLACK:[TYPE.NORMAL, TYPE.BLACK],
};

var CLASSNAME = {};
CLASSNAME[COLOR.LIGHT_RED] = "colorLRed";
CLASSNAME[COLOR.LIGHT_YELLOW] = "colorLYellow";
CLASSNAME[COLOR.LIGHT_GREEN] = "colorLGreen";
CLASSNAME[COLOR.LIGHT_CYAN] = "colorLCyan";
CLASSNAME[COLOR.LIGHT_BLUE] = "colorLBlue";
CLASSNAME[COLOR.LIGHT_MAGENTA] = "colorLMagenta";
CLASSNAME[COLOR.NORMAL_RED] = "colorNRed";
CLASSNAME[COLOR.NORMAL_YELLOW] = "colorNYellow";
CLASSNAME[COLOR.NORMAL_GREEN] = "colorNGreen";
CLASSNAME[COLOR.NORMAL_CYAN] = "colorNCyan";
CLASSNAME[COLOR.NORMAL_BLUE] = "colorNBlue";
CLASSNAME[COLOR.NORMAL_MAGENTA] = "colorNMagenta";
CLASSNAME[COLOR.DARK_RED] = "colorDRed";
CLASSNAME[COLOR.DARK_YELLOW] = "colorDYellow";
CLASSNAME[COLOR.DARK_GREEN] = "colorDGreen";
CLASSNAME[COLOR.DARK_CYAN] = "colorDCyan";
CLASSNAME[COLOR.DARK_BLUE] = "colorDBlue";
CLASSNAME[COLOR.DARK_MAGENTA] = "colorDMagenta";
CLASSNAME[COLOR.NORMAL_WHITE] = "colorNWhite";
CLASSNAME[COLOR.NORMAL_BLACK] = "colorNBlack";

module.exports = {
  TYPE: TYPE,
  COLOR: COLOR,
  CLASSNAME: CLASSNAME,
};
