var keyMirror = require("keymirror");

var TYPE = keyMirror({
  LIGHT: null,
  NORMAL: null,
  DARK: null,
  RED: null,
  YELLOW: null,
  GREEN: null,
  CYAN: null,
  BLUE: null,
  MAGENTA: null,
  WHITE: null,
  BLACK: null,
});

var COLOR = {
  LIGHT_RED:[TYPE.LIGHT, TYPE.RED],
  LIGHT_YELLOW:[TYPE.LIGHT, TYPE.YELLOW],
  LIGHT_GREEN:[TYPE.LIGHT, TYPE.GREEN],
  LIGHT_CYAN:[TYPE.LIGHT, TYPE.CYAN],
  LIGHT_BLUE:[TYPE.LIGHT, TYPE.BLUE],
  LIGHT_MAGENTA:[TYPE.LIGHT, TYPE.MAGENTA],
  NORMAL_RED:[TYPE.NORMAL, TYPE.RED],
  NORMAL_YELLOW:[TYPE.NORMAL, TYPE.YELLOW],
  NORMAL_GREEN:[TYPE.NORMAL, TYPE.GREEN],
  NORMAL_CYAN:[TYPE.NORMAL, TYPE.CYAN],
  NORMAL_BLUE:[TYPE.NORMAL, TYPE.BLUE],
  NORMAL_MAGENTA:[TYPE.NORMAL, TYPE.MAGENTA],
  DARK_RED:[TYPE.DARK, TYPE.RED],
  DARK_YELLOW:[TYPE.DARK, TYPE.YELLOW],
  DARK_GREEN:[TYPE.DARK, TYPE.GREEN],
  DARK_CYAN:[TYPE.DARK, TYPE.CYAN],
  DARK_BLUE:[TYPE.DARK, TYPE.BLUE],
  DARK_MAGENTA:[TYPE.DARK, TYPE.MAGENTA],
  NORMAL_WHITE:[TYPE.NORMAL, TYPE.WHITE],
  NORMAL_BLACK:[TYPE.NORMAL, TYPE.BLACK],
};

module.exports = {
  TYPE: TYPE,
  COLOR: COLOR,
};
